project_id = "pnxaenqtiojctivughrl"

[functions.analyze-cdc]
verify_jwt = false

[functions.approve-cdc]
verify_jwt = false

[functions.generate-lesson-plan]
verify_jwt = false

[functions.generate-teacher-guideline]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false
